name: emoji_extension
description: Emojis for Flutter & Dart (Unicode 16.0) + one, yet powerful emojis String extension
version: 1.2.0
repository: https://github.com/Nikoro/emoji_extension
issue_tracker: https://github.com/Nikoro/emoji_extension/issues
topics: [emoji, emojis, collection, unicode]

environment:
  sdk: ^3.4.0

dependencies:
  collection: 1.19.1

dev_dependencies:
  test: ^1.25.14
  flutter_lints: ^5.0.0

screenshots:
  - description: The emoji extension logo
    path: images/logo.webp
  - description: Emoji Overview App demo
    path: flutter_examples/emoji_overview_app_example/demo.webp
  - description: Emoji Chat App demo
    path: flutter_examples/emoji_chat_app_example/demo.webp
